Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
	end

	config.vm.box = "ubuntu/bionic64"
	config.vm.provision "shell", path: 'vagrantProvision.sh'
	config.vm.provision "file", source: "ansible", destination: "$HOME/ansible"
	config.vm.provision "file", source: "docker", destination: "$HOME/docker"
end