Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
	end

    config.vm.network "private_network", ip: "192.168.1.101",
        virtualbox__intnet: "puppet-network"

	config.vm.box = "ubuntu/bionic64"
	config.vm.hostname = "puppet-agent-01"
	config.vm.provision "shell", path: 'vagrantProvision.sh'
end