---
- hosts: all 
  remote_user: ubuntu
  become: true
  tasks:
   - name: Installing nginx
     apt: name=nginx state=present update_cache=true
     notify:
       - 'Start nginx'
  handlers:
   - name: Start nginx
     service: name=nginx state=started
